name = "hex-resultant"
defaultTargets = ["HexResultant"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "1ca97f372946ecc430fe4f3961ec4220f9bc7706"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "591c146eeee0ef301a110cd33c19cc0cf1e07352"

[[require]]
name = "HexDeterminant"
git = "https://github.com/leanprover/hex-determinant.git"
rev = "b9b21e295175885e2ee20728c8f8a13d00e36124"

[[lean_lib]]
name = "HexResultant"
